{{- $_ := set . "Version" ( splitList "/" .Values.global.github_ref | last ) }}

{{- if or ( eq .Version "master") (eq .Version "werfio2") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
  labels:
    service: {{ .Chart.Name }}-backend
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-backend
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}-backend
    spec:
      imagePullSecrets:
        - name: github-werfio
      containers:
        - name: web
          command: ["nginx", "-g", "daemon off;"]
          image: {{ tuple "web" . | werf_image }}
{{- include "resources" . | indent 10 }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  clusterIP: None
  selector:
    service: {{ .Chart.Name }}-backend
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name }}-backend
  updatePolicy:
    updateMode: "Initial"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-backend
{{- end }}