name: Documentation Validation
on:
  push:
    paths:
      - '.github/workflows/docs_tests.yml'
      - 'cmd/**'
      - 'docs/**'
      - 'README.md'
      - 'README_ru.md'

jobs:

  check_cli_and_readme_partials:
    name: Check CLI and README partials
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: |
          ./scripts/ci/git.sh
          go test ./integration/suites/docs

  check_links:
    container: jekyll/builder:3
    name: Check broken links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: [ru, en]
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Prepare
        run: |
          cd docs
          mkdir -m 777 documentation/.jekyll-cache site/.jekyll-cache _site
          cd documentation
          gem update bundler
          bundle install

      - name: Build (ru)
        if: matrix.lang == 'ru'
        run: |
          cd docs/site
          bundle exec jekyll build -d ../_site/ --config _config.yml,_config_ru.yml
          cd ../documentation
          bundle exec jekyll build -d ../_site/documentation --config _config.yml,_config_ru.yml

      - name: Build (en)
        if: matrix.lang == 'en'
        run: |
          cd docs/site
          bundle exec jekyll build -d ../_site/ --config _config.yml
          cd ../documentation
          bundle exec jekyll build -d ../_site/documentation --config _config.yml

      - name: Check links
        run: |
          cd docs/documentation
          bundle exec htmlproofer \
            --allow-hash-href \
            --empty-alt-ignore \
            --check_html \
            --url_ignore "/localhost/,/example.com/,/atseashop.com/,/https\:\/\/t.me/,/.slack.com/,/habr.com/,/cncf.io/,/\/guides/,/\/introduction\.html/,/\/installation\.html/,/werf_yaml.html#configuring-cleanup-policies/" \
            --url_swap "documentation/v[0-9]+[^/]+/:documentation/" \
            --http-status-ignore 0 \
            ../_site/
